name: Send Weather to LINE

on:
  schedule:
    - cron: '0 0 * * *'  # 毎朝9:00 JST（UTC+0で0:00）
  workflow_dispatch:      # 手動実行も可

jobs:
  send-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run weather script
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: python weather_line_push.py
